        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 26 16:45:34 2025
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE DIAGNOSTIC_CREATELU__genmod
          INTERFACE 
            SUBROUTINE DIAGNOSTIC_CREATELU(YEAR,CDAYPYR,FILENAME,NUMVARS&
     &,SUBCOUNT,LONSIB,LATSIB,SITESIB,LGAREA,LGREF,PERIOD_START,        &
     &PERIOD_STEP,NSAVEPERFILE,NAMEVARS,LISTVARS,FILEID,VARIDS,TIMEID)
              INTEGER(KIND=4), INTENT(IN) :: SUBCOUNT
              INTEGER(KIND=4), INTENT(IN) :: NUMVARS
              INTEGER(KIND=4), INTENT(IN) :: YEAR
              INTEGER(KIND=4), INTENT(IN) :: CDAYPYR
              CHARACTER(LEN=512), INTENT(IN) :: FILENAME
              REAL(KIND=4), INTENT(IN) :: LONSIB(SUBCOUNT)
              REAL(KIND=4), INTENT(IN) :: LATSIB(SUBCOUNT)
              CHARACTER(LEN=6), INTENT(IN) :: SITESIB(SUBCOUNT)
              REAL(KIND=4), INTENT(IN) :: LGAREA(SUBCOUNT,10)
              INTEGER(KIND=4), INTENT(IN) :: LGREF(SUBCOUNT,10)
              REAL(KIND=8), INTENT(IN) :: PERIOD_START
              REAL(KIND=8), INTENT(IN) :: PERIOD_STEP
              INTEGER(KIND=4), INTENT(IN) :: NSAVEPERFILE
              CHARACTER(LEN=21), INTENT(IN) :: NAMEVARS(NUMVARS)
              CHARACTER(LEN=100), INTENT(IN) :: LISTVARS(NUMVARS)
              INTEGER(KIND=4), INTENT(OUT) :: FILEID
              INTEGER(KIND=4), INTENT(OUT) :: VARIDS(NUMVARS)
              INTEGER(KIND=4), INTENT(OUT) :: TIMEID
            END SUBROUTINE DIAGNOSTIC_CREATELU
          END INTERFACE 
        END MODULE DIAGNOSTIC_CREATELU__genmod
