        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 26 16:45:34 2025
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE DIAGNOSTIC_CREATEG__genmod
          INTERFACE 
            SUBROUTINE DIAGNOSTIC_CREATEG(YEAR,CURDAY_PER_YEAR,FILENAME,&
     &NUMVARS,SUBCOUNT,LONSIB,LATSIB,SITESIB,PERIOD_START,PERIOD_STEP,  &
     &NSAVEPERFILE,NAMEVARS,LISTVARS,FILEID,VARIDS,TIMEID)
              INTEGER(KIND=4), INTENT(IN) :: SUBCOUNT
              INTEGER(KIND=4), INTENT(IN) :: NUMVARS
              INTEGER(KIND=4), INTENT(IN) :: YEAR
              INTEGER(KIND=4), INTENT(IN) :: CURDAY_PER_YEAR
              CHARACTER(LEN=512), INTENT(IN) :: FILENAME
              REAL(KIND=4), INTENT(IN) :: LONSIB(SUBCOUNT)
              REAL(KIND=4), INTENT(IN) :: LATSIB(SUBCOUNT)
              CHARACTER(LEN=6), INTENT(IN) :: SITESIB(SUBCOUNT)
              REAL(KIND=8), INTENT(IN) :: PERIOD_START
              REAL(KIND=8), INTENT(IN) :: PERIOD_STEP
              INTEGER(KIND=4), INTENT(IN) :: NSAVEPERFILE
              CHARACTER(LEN=21), INTENT(IN) :: NAMEVARS(NUMVARS)
              CHARACTER(LEN=100), INTENT(IN) :: LISTVARS(NUMVARS)
              INTEGER(KIND=4), INTENT(OUT) :: FILEID
              INTEGER(KIND=4), INTENT(OUT) :: VARIDS(NUMVARS)
              INTEGER(KIND=4), INTENT(OUT) :: TIMEID
            END SUBROUTINE DIAGNOSTIC_CREATEG
          END INTERFACE 
        END MODULE DIAGNOSTIC_CREATEG__genmod
